POST  http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userType":"user",
    "userName":"bhanu",
    "password":"bhanu",
    "email":"bhanu@gmail.com"
}


###login check
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "userName":"bhanu",
    "password":"bhanu"
    
}
###reading articles
get http://localhost:4000/user-api/articles


###comment
post http://localhost:4000/user-api/comment
Content-Type: application/json

{
    "articleid":"1714056991",
    "username":"ravi",
    "comment":"this is usefull article"
}